on:
  push:
    branches:
      - main
      - master

name: deploy-to-connect

jobs:
  deploy-to-connect:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
    
      - name: Deploy geyser app
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://${{ secrets.CONNECT_API_KEY }}@colorado.rstudio.com/rsc
          access-type: logged_in
          dir: |
            ./geyser/
